using System.Collections.Generic;

namespace ODF.Domain.Constants
{
	public static class MimeTypes
	{
		public static List<string> ExcludedMimeTypes => _excludedMimeTypes;

		private static readonly List<string> _excludedMimeTypes = new()
		{
			"application/javascript",
			"application/msword",
			"application/octet-stream",
			"application/ogg",
			"application/pdf",
			"application/rtf",
			"application/vnd.apple.installer+xml",
			"application/vnd.mozilla.xul+xml",
			"application/vnd.ms-excel",
			"application/vnd.ms-fontobject",
			"application/vnd.ms-powerpoint",
			"application/vnd.oasis.opendocument.presentation",
			"application/vnd.oasis.opendocument.spreadsheet",
			"application/vnd.oasis.opendocument.text",
			"application/vnd.openxmlformats-officedocument.presentationml.presentation",
			"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
			"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
			"application/vnd.visio",
			"application/x-csh",
			"application/x-sh",
			"application/x-shockwave-flash",
			"application/xhtml+xml",
			"application/xml",
			"audio/3gpp",
			"audio/3gpp2",
			"audio/aac",
			"audio/midi",
			"audio/x-midi",
			"audio/mpeg",
			"audio/ogg",
			"audio/opus",
			"audio/wav",
			"audio/webm",
			"font/otf",
			"font/ttf",
			"font/woff",
			"font/woff2",
			"image/bmp",
			"image/gif",
			"image/jpeg",
			"image/png",
			"image/svg+xml",
			"image/tiff",
			"image/vnd.microsoft.icon",
			"image/webp",
			"text/calendar",
			"text/css",
			"text/csv",
			"text/html",
			"text/javascript",
			"text/plain",
			"text/xml",
			"video/3gpp",
			"video/3gpp2",
			"video/mp2t",
			"video/mpeg",
			"video/ogg",
			"video/webm",
			"video/x-msvideo",
		};
	}
}
