{
 "title": "ODF",
 "time": { "from": "now-5m", "to": "now-1m" },
 "panels": [
  {
   "title": "hosting requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_requests_per_second_total{}"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "system_net_http_requests_failed_total{}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_hosting_requests_per_second_total{}"
    }
   ]
  },
  {
   "title": "Health checks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"Redis_DB\"}",
     "legendFormat": "Redis health"
    },
    {
     "expr": "healthcheck{healthcheck=\"Elastic_DB\"}",
     "legendFormat": "Elastic health"
    }
   ]
  },
  {
   "title": "Request queue length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_request_queue_length{}"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_total_connections{}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(system_runtime_cpu_usage{}[$__interval])"
    }
   ]
  },
  {
   "title": "process_runtime_dotnet_timer_count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_timer_count"
    }
   ]
  },
  {
   "title": "http_server_duration_ms_count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_duration_ms_count{}[$__interval])"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dotnet_total_memory_bytes{}[$__interval])"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "level: Error",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}