global:
  scrape_timeout: 60s
  query_log_file: /etc/prometheus/query.log

scrape_configs:
  - job_name: 'odf-api'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8982']

  - job_name: 'odf-api-hc'
    scrape_interval: 10s
    metrics_path: '/health'
    static_configs:
      - targets: ['api:8982']