version: "3.7"

services:
  redis:
    container_name: odf-redis
    image: redis:latest
    restart: always
    ports: # Hide in case of production
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PW}
    networks:
      - odf-redis
    volumes:
      - redis_data:/var/lib/redis
      
  elasticsearch:
    ports: # Hide in case of production
      - ${ELASTIC_PORT}:9200
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch-odf
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PW}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-odf
    volumes:
       - elastic_data:/var/lib/elastic
  
  api:
    image: ghcr.io/rades98/odf.api:main
    restart: always
    container_name: odf-api
    ports:
      - ${WEB_API_PORT_HTTP}:${WEB_API_PORT_HTTP} #DEV
      # - ${WEB_API_PORT}:${WEB_API_PORT} #PROD
    environment:
      ASPNETCORE_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      # ASPNETCORE_HTTPS_PORT: "${WEB_API_PORT}" #PROD
      ASPNETCORE_URLS: "http://*:${WEB_API_PORT_HTTP};" #https://*:${WEB_API_PORT} swap for PROD
      ApiSettings__ApiUrl: ${WEB_API_RESPONSE_PATH}
      ApiSettings__FrontEndUrl: ${FE_URL}
      ApiSettings__AdminPw: ${ADMIN_PW}
      ElasticsearchSettings__DefaultIndex: "odf-articles"
      ElasticsearchSettings__Nodes__0: http://elasticsearch:${ELASTIC_PORT}
      ElasticsearchSettings__Password: ${ELASTIC_PW}
      RedisSettings__Url: redis:${REDIS_PORT}
      RedisSettings__Password: ${REDIS_PW}
     
    volumes:
      - ${DOTNET_SECRETS}:/root/.microsoft/usersecrets
      - ${DOCTNET_HTTPS}:/root/.aspnet/https/
    depends_on:
      - elasticsearch
      - redis
    networks:
      - elastic-odf
      - odf-redis
      - webapi-network
      - grafana_stuff

  prometheus:
    image: prom/prometheus
    restart: always
    container_name: odf-prometheus
    volumes:
      - ./var/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
    networks:
      - webapi-network
      - grafana_stuff
    
  grafana:
    image: grafana/grafana:8.1.5
    container_name: odf-grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./var/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./var/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_INSTALL_PLUGINS=simpod-json-datasource
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
    depends_on:
      - prometheus
      - elasticsearch
      - api
    networks:
      - grafana_stuff
      - webapi-network
      - elastic-odf

networks:
  elastic-odf:
  odf-redis:
  webapi-network:
  grafana_stuff:
    driver: bridge

volumes:
  elastic_data:
  redis_data:
  grafana_data:
