version: "3.7"

services:
  redis:
    container_name: odf-redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - odf-redis
    volumes:
      - ./var/lib/redis:/redis

  redis-commander-odf:
    image: rediscommander/redis-commander
    container_name: odf-redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=redis
      - REDIS_PORT=6379
    ports:
      - "8081:8081"
    networks:
      - odf-redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch-odf
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PW}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elastic-odf
    volumes:
       - ./var/lib/elastic:/elastic

  kibana-odf:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana-odf
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PW}
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    networks:
        - elastic-odf
  
  api:
    restart: always
    container_name: odf-api
    build: .
    ports:
      - "8981:${WEB_API_PORT}"
    environment:
      ASPNETCORE_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      ASPNETCORE_HTTPS_PORT: "${WEB_API_PORT}"
      ASPNETCORE_URLS: "http://*:${WEB_API_PORT_HTTP};https://*:${WEB_API_PORT}"
      ApiSettings__ApiUrl: "https://127.0.0.1:${WEB_API_PORT}"
      ElasticsearchSettings__DefaultIndex: "odf-articles"
      ElasticsearchSettings__Nodes__0: http://elasticsearch:9200
      ElasticsearchSettings__Password: "kjKSzpjAeyakMiHesoyAm"
      RedisSettings__Url: "redis:6379"
     
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    depends_on:
      - elasticsearch
      - redis
    networks:
      - elastic-odf
      - odf-redis
      - webapi-network
      - grafana_stuff

  # certbot:
  #   container_name: odf-certbot
  #   image: certbot/certbot
  #   volumes:
  #     - ./var/lib/certbot/certs:/etc/letsencrypt
  #     - ./var/lib/certbot/www:/var/www/certbot
  #   command: certonly --webroot --webroot-path=/var/www/certbot ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN_NAME} --staging
  #   depends_on:
  #     - api
  #   networks:
  #     - webapi-network

  prometheus:
    image: prom/prometheus
    restart: always
    container_name: odf-prometheus
    volumes:
      - ./var/lib/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
    networks:
      - webapi-network
      - grafana_stuff
    
  grafana:
    image: grafana/grafana:8.1.5
    container_name: odf-grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./var/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_INSTALL_PLUGINS=simpod-json-datasource
    depends_on:
      - prometheus
      - api
    networks:
      - grafana_stuff
      - webapi-network

networks:
  elastic-odf:
  odf-redis:
  webapi-network:
  grafana_stuff:
    driver: bridge

volumes:
  esdata:
    driver: local
  grafana_data:

# RTFM
# IN POWERSHELL
# cd .\ODF.API\
# dotnet dev-certs https -ep $env:USERPROFILE\.aspnet\https\ODF.API.pfx -p kjkszpj
# dotnet dev-certs https --trust
# dotnet user-secrets set "Kestrel:Certificates:Development:Password" "kjkszpj"
# cd ../
# docker-compose up  -d 
# after everything is running, run  docker-compose up --build -d 

#to down
# docker-compose down --remove-orphans

#API LOGIN: admin : heslopyco

#To see logs type to cmd docker logs odf-api

#To see shit in kibana: 127.0.0.1:5601 -> elastic : kjKSzpjAeyakMiHesoyAm
# - Analytics
#    |-- Discover
#         |-- Create index pattern
#              |-- select odf-api-development + create
#    |-- Discover again
#  CG! u can see shit