name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag odfapi:$(date +%s) . 
